### ISSUE TITLE
Gamepad doesn't show up

### ISSUE THREAD

**Issue by ClementRouvroy** [Jon-Davis/Godot-Virtual-Joystick#1]
Hi, i have add a control, attach the script.
But the joystick doesn't show up, any idea?

**Comment by Jon-Davis** [comment]
I haven't used godot in a while but i loaded it up and it seems there is a new function called draw_circle in godot that wasn't in it when i made the class, so there seemed to be a conflict, I updated the function definition to hopefully resolve the conflict. Try the new version of the code.

Additionally the gamepad circle won't show in the editor, but it should show when you run the game, so long as the persistence boolean is set. When you click on the control node in the scene, look over at the inspector, under the inspector there should be script variables, the persistent script variable determines whether the controller is always active or if it is only active when touched.
